import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Notes App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello World</h1>
      <Link href="/new">
        <h2><button>View Notes</button></h2>
      </Link>
      <Link href="/new">
        <h2><button>New Note</button></h2>
      </Link>
    </>
  )
}
